/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author radit
 */

import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JOptionPane;

public class SmartConverter extends javax.swing.JFrame {

    /**
     * Creates new form SmartConverter
     */
    public SmartConverter() {
        initComponents();
        
           jScrollPane2.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER
         );
         jScrollPane2.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
         );
         
         jScrollPane3.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER
         );
         jScrollPane3.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
         );
         
         jScrollPane4.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER
         );
         jScrollPane4.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
         );
         
         jScrollPane5.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER
         );
         jScrollPane5.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
         );
         
         jScrollPane6.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER
         );
         jScrollPane6.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
         );

        
        txtDesc.setEditable(false);
        txtDesc.setFocusable(false);
        txtDesc.setCursor(null);
        txtDesc.setOpaque(false);
        txtDesc.setBorder(null);
        txtDesc.setLineWrap(true);
        txtDesc.setWrapStyleWord(true);
        
        txtDesc1.setEditable(false);
        txtDesc1.setFocusable(false);
        txtDesc1.setCursor(null);
        txtDesc1.setOpaque(false);
        txtDesc1.setBorder(null);
        txtDesc1.setLineWrap(true);
        txtDesc1.setWrapStyleWord(true);
        
        txtDesc2.setEditable(false);
        txtDesc2.setFocusable(false);
        txtDesc2.setCursor(null);
        txtDesc2.setOpaque(false);
        txtDesc2.setBorder(null);
        txtDesc2.setLineWrap(true);
        txtDesc2.setWrapStyleWord(true);
        
        txtDesc3.setEditable(false);
        txtDesc3.setFocusable(false);
        txtDesc3.setCursor(null);
        txtDesc3.setOpaque(false);
        txtDesc3.setBorder(null);
        txtDesc3.setLineWrap(true);
        txtDesc3.setWrapStyleWord(true);
        
        txtDesc4.setEditable(false);
        txtDesc4.setFocusable(false);
        txtDesc4.setCursor(null);
        txtDesc4.setOpaque(false);
        txtDesc4.setBorder(null);
        txtDesc4.setLineWrap(true);
        txtDesc4.setWrapStyleWord(true);
        
        txtDesc.setEditable(false);
        txtDesc.setFocusable(false);
        txtDesc.setCursor(null);
        txtDesc.setOpaque(false);
        txtDesc.setBorder(null);
        txtDesc.setLineWrap(true);
        txtDesc.setWrapStyleWord(true);
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_time = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel004 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel005 = new javax.swing.JLabel();
        btn_data = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel001 = new javax.swing.JLabel();
        btn_weight = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel003 = new javax.swing.JLabel();
        btn_lenght = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel002 = new javax.swing.JLabel();
        garis = new javax.swing.JSeparator();
        btn_exit = new javax.swing.JButton();
        txtJudul3 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JLabel();
        txtJudul1 = new javax.swing.JLabel();
        timeCard = new javax.swing.JPanel();
        iconCard = new javax.swing.JLabel();
        txtJudul2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        weightCard = new javax.swing.JPanel();
        iconCard1 = new javax.swing.JLabel();
        txtJudul4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDesc1 = new javax.swing.JTextArea();
        lenghtCard = new javax.swing.JPanel();
        iconCard2 = new javax.swing.JLabel();
        txtJudul5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDesc2 = new javax.swing.JTextArea();
        dataCard = new javax.swing.JPanel();
        iconCard3 = new javax.swing.JLabel();
        txtJudul6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDesc3 = new javax.swing.JTextArea();
        Cardpane4 = new javax.swing.JPanel();
        iconCard4 = new javax.swing.JLabel();
        txtJudul7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDesc4 = new javax.swing.JTextArea();
        jMenuBar3 = new javax.swing.JMenuBar();
        menuExit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuGit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(232, 240, 254));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(31, 41, 55));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_time.setBackground(new java.awt.Color(31, 41, 55));
        btn_time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_timeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_timeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_timeMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_time_35px.png"))); // NOI18N

        jLabel004.setBackground(new java.awt.Color(255, 255, 255));
        jLabel004.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel004.setForeground(new java.awt.Color(255, 255, 255));
        jLabel004.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel004.setText("Time");

        javax.swing.GroupLayout btn_timeLayout = new javax.swing.GroupLayout(btn_time);
        btn_time.setLayout(btn_timeLayout);
        btn_timeLayout.setHorizontalGroup(
            btn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_timeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel004)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        btn_timeLayout.setVerticalGroup(
            btn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_timeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_timeLayout.createSequentialGroup()
                        .addComponent(jLabel004)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 380, 70));

        btn_home.setBackground(new java.awt.Color(31, 41, 55));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_home_35px_1.png"))); // NOI18N

        jLabel005.setBackground(new java.awt.Color(255, 255, 255));
        jLabel005.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel005.setForeground(new java.awt.Color(255, 255, 255));
        jLabel005.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel005.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel005)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_homeLayout.createSequentialGroup()
                        .addComponent(jLabel005)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 380, 70));

        btn_data.setBackground(new java.awt.Color(31, 41, 55));
        btn_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dataMousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_save_as_35px.png"))); // NOI18N

        jLabel001.setBackground(new java.awt.Color(255, 255, 255));
        jLabel001.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel001.setForeground(new java.awt.Color(255, 255, 255));
        jLabel001.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel001.setText("Data");

        javax.swing.GroupLayout btn_dataLayout = new javax.swing.GroupLayout(btn_data);
        btn_data.setLayout(btn_dataLayout);
        btn_dataLayout.setHorizontalGroup(
            btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel001)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        btn_dataLayout.setVerticalGroup(
            btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dataLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_dataLayout.createSequentialGroup()
                        .addComponent(jLabel001)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 380, 70));

        btn_weight.setBackground(new java.awt.Color(31, 41, 55));
        btn_weight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_weightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_weightMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_weightMousePressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_weight_kg_35px.png"))); // NOI18N

        jLabel003.setBackground(new java.awt.Color(255, 255, 255));
        jLabel003.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel003.setForeground(new java.awt.Color(255, 255, 255));
        jLabel003.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel003.setText("Weight");

        javax.swing.GroupLayout btn_weightLayout = new javax.swing.GroupLayout(btn_weight);
        btn_weight.setLayout(btn_weightLayout);
        btn_weightLayout.setHorizontalGroup(
            btn_weightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_weightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel003)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        btn_weightLayout.setVerticalGroup(
            btn_weightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_weightLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_weightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_weightLayout.createSequentialGroup()
                        .addComponent(jLabel003)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 380, 70));

        btn_lenght.setBackground(new java.awt.Color(31, 41, 55));
        btn_lenght.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lenghtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lenghtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_lenghtMousePressed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_length_35px.png"))); // NOI18N

        jLabel002.setBackground(new java.awt.Color(255, 255, 255));
        jLabel002.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel002.setForeground(new java.awt.Color(255, 255, 255));
        jLabel002.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel002.setText("Lenght");

        javax.swing.GroupLayout btn_lenghtLayout = new javax.swing.GroupLayout(btn_lenght);
        btn_lenght.setLayout(btn_lenghtLayout);
        btn_lenghtLayout.setHorizontalGroup(
            btn_lenghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_lenghtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel002)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        btn_lenghtLayout.setVerticalGroup(
            btn_lenghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_lenghtLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_lenghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_lenghtLayout.createSequentialGroup()
                        .addComponent(jLabel002)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_lenght, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 380, 70));
        sidepane.add(garis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 320, 10));

        btn_exit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        sidepane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 70, -1));

        txtJudul3.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtJudul3.setForeground(new java.awt.Color(255, 255, 255));
        txtJudul3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul3.setText("Smart Converter");
        sidepane.add(txtJudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, -1));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 380, 850));

        txtJudul.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        txtJudul.setForeground(new java.awt.Color(31, 41, 55));
        txtJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul.setText("Welcome to Smart Converter");
        bg.add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 660, 80));

        txtJudul1.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtJudul1.setForeground(new java.awt.Color(129, 131, 138));
        txtJudul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul1.setText("Select a category to start!");
        bg.add(txtJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 290, -1));

        timeCard.setBackground(new java.awt.Color(255, 255, 255));
        timeCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        timeCard.setMaximumSize(new java.awt.Dimension(200, 260));
        timeCard.setName(""); // NOI18N
        timeCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timeCardMousePressed(evt);
            }
        });

        iconCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N

        txtJudul2.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul2.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        txtJudul2.setForeground(new java.awt.Color(31, 41, 55));
        txtJudul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul2.setText("Time Converter");

        jScrollPane2.setEnabled(false);

        txtDesc.setEditable(false);
        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtDesc.setForeground(new java.awt.Color(102, 102, 102));
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        txtDesc.setText("Convert between seconds, minutes, hours and days");
        txtDesc.setWrapStyleWord(true);
        txtDesc.setAutoscrolls(false);
        txtDesc.setFocusable(false);
        jScrollPane2.setViewportView(txtDesc);

        javax.swing.GroupLayout timeCardLayout = new javax.swing.GroupLayout(timeCard);
        timeCard.setLayout(timeCardLayout);
        timeCardLayout.setHorizontalGroup(
            timeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeCardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(iconCard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeCardLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(timeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJudul2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        timeCardLayout.setVerticalGroup(
            timeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeCardLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconCard, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtJudul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bg.add(timeCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 210, 320));

        weightCard.setBackground(new java.awt.Color(255, 255, 255));
        weightCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        weightCard.setMaximumSize(new java.awt.Dimension(200, 260));
        weightCard.setName(""); // NOI18N
        weightCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                weightCardMousePressed(evt);
            }
        });

        iconCard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2.png"))); // NOI18N

        txtJudul4.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul4.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        txtJudul4.setForeground(new java.awt.Color(31, 41, 55));
        txtJudul4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul4.setText("Weight Converter");

        jScrollPane3.setEnabled(false);

        txtDesc1.setEditable(false);
        txtDesc1.setColumns(20);
        txtDesc1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtDesc1.setForeground(new java.awt.Color(102, 102, 102));
        txtDesc1.setLineWrap(true);
        txtDesc1.setRows(5);
        txtDesc1.setText("Convert between miligrams, grams, kilograms and tons");
        txtDesc1.setWrapStyleWord(true);
        txtDesc1.setAutoscrolls(false);
        txtDesc1.setFocusable(false);
        jScrollPane3.setViewportView(txtDesc1);

        javax.swing.GroupLayout weightCardLayout = new javax.swing.GroupLayout(weightCard);
        weightCard.setLayout(weightCardLayout);
        weightCardLayout.setHorizontalGroup(
            weightCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weightCardLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(weightCardLayout.createSequentialGroup()
                .addGroup(weightCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weightCardLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(iconCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(weightCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtJudul4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        weightCardLayout.setVerticalGroup(
            weightCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightCardLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtJudul4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bg.add(weightCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 210, 320));

        lenghtCard.setBackground(new java.awt.Color(255, 255, 255));
        lenghtCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        lenghtCard.setMaximumSize(new java.awt.Dimension(200, 260));
        lenghtCard.setName(""); // NOI18N
        lenghtCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lenghtCardMousePressed(evt);
            }
        });

        iconCard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.png"))); // NOI18N

        txtJudul5.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul5.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        txtJudul5.setForeground(new java.awt.Color(31, 41, 55));
        txtJudul5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul5.setText("Lenght Converter");

        jScrollPane4.setEnabled(false);

        txtDesc2.setEditable(false);
        txtDesc2.setColumns(20);
        txtDesc2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtDesc2.setForeground(new java.awt.Color(102, 102, 102));
        txtDesc2.setLineWrap(true);
        txtDesc2.setRows(5);
        txtDesc2.setText("Convert between milimeters, centimeters, meters and kilometers");
        txtDesc2.setWrapStyleWord(true);
        txtDesc2.setAutoscrolls(false);
        txtDesc2.setFocusable(false);
        jScrollPane4.setViewportView(txtDesc2);

        javax.swing.GroupLayout lenghtCardLayout = new javax.swing.GroupLayout(lenghtCard);
        lenghtCard.setLayout(lenghtCardLayout);
        lenghtCardLayout.setHorizontalGroup(
            lenghtCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lenghtCardLayout.createSequentialGroup()
                .addGroup(lenghtCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lenghtCardLayout.createSequentialGroup()
                        .addGroup(lenghtCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lenghtCardLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(iconCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lenghtCardLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lenghtCardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtJudul5)))
                .addContainerGap())
        );
        lenghtCardLayout.setVerticalGroup(
            lenghtCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lenghtCardLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtJudul5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bg.add(lenghtCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 210, 320));

        dataCard.setBackground(new java.awt.Color(255, 255, 255));
        dataCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        dataCard.setMaximumSize(new java.awt.Dimension(200, 260));
        dataCard.setName(""); // NOI18N
        dataCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dataCardMousePressed(evt);
            }
        });

        iconCard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4.png"))); // NOI18N

        txtJudul6.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul6.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        txtJudul6.setForeground(new java.awt.Color(31, 41, 55));
        txtJudul6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul6.setText("Data Converter");

        jScrollPane5.setEnabled(false);

        txtDesc3.setEditable(false);
        txtDesc3.setColumns(20);
        txtDesc3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtDesc3.setForeground(new java.awt.Color(102, 102, 102));
        txtDesc3.setLineWrap(true);
        txtDesc3.setRows(5);
        txtDesc3.setText("Convert between Kilobytes, Megabytes, Gigabytes and Terabytes");
        txtDesc3.setWrapStyleWord(true);
        txtDesc3.setAutoscrolls(false);
        txtDesc3.setFocusable(false);
        jScrollPane5.setViewportView(txtDesc3);

        javax.swing.GroupLayout dataCardLayout = new javax.swing.GroupLayout(dataCard);
        dataCard.setLayout(dataCardLayout);
        dataCardLayout.setHorizontalGroup(
            dataCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataCardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(iconCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataCardLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(dataCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtJudul6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        dataCardLayout.setVerticalGroup(
            dataCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataCardLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtJudul6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bg.add(dataCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 250, 210, 320));

        Cardpane4.setBackground(new java.awt.Color(255, 255, 255));
        Cardpane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        Cardpane4.setMaximumSize(new java.awt.Dimension(200, 260));
        Cardpane4.setName(""); // NOI18N

        iconCard4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5.png"))); // NOI18N

        txtJudul7.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul7.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        txtJudul7.setForeground(new java.awt.Color(31, 41, 55));
        txtJudul7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul7.setText("About Smart Converter");

        jScrollPane6.setEnabled(false);

        txtDesc4.setEditable(false);
        txtDesc4.setColumns(20);
        txtDesc4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtDesc4.setForeground(new java.awt.Color(102, 102, 102));
        txtDesc4.setLineWrap(true);
        txtDesc4.setRows(5);
        txtDesc4.setText("Easily converts between units of a time, weight, lenght, and digital data storage.");
        txtDesc4.setWrapStyleWord(true);
        txtDesc4.setAutoscrolls(false);
        txtDesc4.setFocusable(false);
        jScrollPane6.setViewportView(txtDesc4);

        javax.swing.GroupLayout Cardpane4Layout = new javax.swing.GroupLayout(Cardpane4);
        Cardpane4.setLayout(Cardpane4Layout);
        Cardpane4Layout.setHorizontalGroup(
            Cardpane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cardpane4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(iconCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Cardpane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJudul7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        Cardpane4Layout.setVerticalGroup(
            Cardpane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cardpane4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(iconCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(Cardpane4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtJudul7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(Cardpane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 910, 190));

        menuExit.setText("File");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuExitMouseExited(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuExit.add(jMenuItem1);

        jMenuBar3.add(menuExit);

        jMenu1.setText("Help");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });

        menuGit.setText("GItHub");
        menuGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGitActionPerformed(evt);
            }
        });
        jMenu1.add(menuGit);

        jMenuBar3.add(jMenu1);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        setColor(btn_home);
       resetColor(btn_time);
       resetColor(btn_weight);
       resetColor(btn_lenght);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_timeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timeMouseEntered
        // TODO add your handling code here:
         setColor(btn_time);
       resetColor(btn_home);
       resetColor(btn_weight);
       resetColor(btn_lenght);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_timeMouseEntered

    private void btn_weightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weightMouseEntered
        // TODO add your handling code here:
         setColor(btn_weight);
       resetColor(btn_time);
       resetColor(btn_home);
       resetColor(btn_lenght);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_weightMouseEntered

    private void btn_lenghtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lenghtMouseEntered
        // TODO add your handling code here:
         setColor(btn_lenght);
       resetColor(btn_time);
       resetColor(btn_weight);
       resetColor(btn_home);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_lenghtMouseEntered

    private void btn_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataMouseEntered
        // TODO add your handling code here:
         setColor(btn_data);
       resetColor(btn_time);
       resetColor(btn_weight);
       resetColor(btn_lenght);
       resetColor(btn_home);
    }//GEN-LAST:event_btn_dataMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        resetColor(btn_home);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_timeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timeMouseExited
        // TODO add your handling code here:
        resetColor(btn_time);
    }//GEN-LAST:event_btn_timeMouseExited

    private void btn_weightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weightMouseExited
        // TODO add your handling code here:
        resetColor(btn_weight);
    }//GEN-LAST:event_btn_weightMouseExited

    private void btn_lenghtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lenghtMouseExited
        // TODO add your handling code here:
        resetColor(btn_lenght);
    }//GEN-LAST:event_btn_lenghtMouseExited

    private void btn_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataMouseExited
        // TODO add your handling code here:
        resetColor(btn_data);
    }//GEN-LAST:event_btn_dataMouseExited

    private void btn_timeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timeMousePressed
        // TODO add your handling code here:
        time t = new time();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_timeMousePressed

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        SmartConverter h = new SmartConverter();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_weightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weightMousePressed
        // TODO add your handling code here:
        weight w = new weight();
        w.setVisible(true);
        w.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_weightMousePressed

    private void btn_lenghtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lenghtMousePressed
        // TODO add your handling code here:
        lenght l = new lenght();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_lenghtMousePressed

    private void btn_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataMousePressed
        // TODO add your handling code here:
        data d = new data();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_dataMousePressed

    private void timeCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeCardMousePressed
        // TODO add your handling code here:
        time t = new time();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_timeCardMousePressed

    private void weightCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightCardMousePressed
        // TODO add your handling code here:
        weight w = new weight();
        w.setVisible(true);
        w.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_weightCardMousePressed

    private void lenghtCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lenghtCardMousePressed
        // TODO add your handling code here:
        lenght l = new lenght();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lenghtCardMousePressed

    private void dataCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataCardMousePressed
        // TODO add your handling code here:
          data d = new data();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_dataCardMousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitMouseExited

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseExited

    private void menuGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGitActionPerformed
        // TODO add your handling code here:
         try {
        java.awt.Desktop.getDesktop().browse(
            new java.net.URI("https://github.com/ybyrdt")
        );
    } catch (Exception e) {
      JOptionPane.showMessageDialog(
              this,
              "Gagal membuka link",
              "Error",
              JOptionPane.ERROR_MESSAGE
      );
    }
    }//GEN-LAST:event_menuGitActionPerformed

    
    void setColor(JPanel panel){
        panel.setBackground(new Color(31,41,75));
    }
    
    void resetColor(JPanel panel){
         panel.setBackground(new Color(31,41,55));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cardpane4;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_data;
    private javax.swing.JButton btn_exit;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_lenght;
    private javax.swing.JPanel btn_time;
    private javax.swing.JPanel btn_weight;
    private javax.swing.JPanel dataCard;
    private javax.swing.JSeparator garis;
    private javax.swing.JLabel iconCard;
    private javax.swing.JLabel iconCard1;
    private javax.swing.JLabel iconCard2;
    private javax.swing.JLabel iconCard3;
    private javax.swing.JLabel iconCard4;
    private javax.swing.JLabel jLabel001;
    private javax.swing.JLabel jLabel002;
    private javax.swing.JLabel jLabel003;
    private javax.swing.JLabel jLabel004;
    private javax.swing.JLabel jLabel005;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel lenghtCard;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuGit;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel timeCard;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextArea txtDesc1;
    private javax.swing.JTextArea txtDesc2;
    private javax.swing.JTextArea txtDesc3;
    private javax.swing.JTextArea txtDesc4;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtJudul1;
    private javax.swing.JLabel txtJudul2;
    private javax.swing.JLabel txtJudul3;
    private javax.swing.JLabel txtJudul4;
    private javax.swing.JLabel txtJudul5;
    private javax.swing.JLabel txtJudul6;
    private javax.swing.JLabel txtJudul7;
    private javax.swing.JPanel weightCard;
    // End of variables declaration//GEN-END:variables
}
