/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author radit
 */

import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;



public class time extends javax.swing.JFrame implements Converter {

    /**
     * Creates new form SmartConverter
     */
    public time() {
        initComponents();
        
        cmbFrom.removeAllItems();
        cmbTo.removeAllItems();
        
        cmbFrom.addItem("-- Choose --");
        cmbFrom.addItem("Second");
        cmbFrom.addItem("Minute");
        cmbFrom.addItem("Hour");
        cmbFrom.addItem("Day");
        
        cmbTo.addItem("-- Choose --");
        cmbTo.addItem("Second");
        cmbTo.addItem("Minute");
        cmbTo.addItem("Hour");
        cmbTo.addItem("Day");
        
        cmbFrom.setSelectedIndex(0);
        cmbTo.setSelectedIndex(0);
        
        txtResult.setEditable(false);
        txtResult.setFocusable(false);
        txtResult.setBackground(Color.WHITE);
        txtResult.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtResult.setText("0");
        
        
    }

    
    @Override
    public double convert(double input, String from, String to) {
        double faktorFrom = 1;
        double faktorTo = 1;

        if (from.equals("Second")) faktorFrom = 1;
        else if (from.equals("Minute")) faktorFrom = 60;
        else if (from.equals("Hour")) faktorFrom = 3600;
        else if (from.equals("Day")) faktorFrom = 86400;

        if (to.equals("Second")) faktorTo = 1;
        else if (to.equals("Minute")) faktorTo = 60;
        else if (to.equals("Hour")) faktorTo = 3600;
        else if (to.equals("Day")) faktorTo = 86400;

        return (input * faktorFrom) / faktorTo;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_time = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel004 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel005 = new javax.swing.JLabel();
        btn_data = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel001 = new javax.swing.JLabel();
        btn_weight = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel003 = new javax.swing.JLabel();
        btn_lenght = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel002 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JLabel();
        garis = new javax.swing.JSeparator();
        btn_exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtJudul1 = new javax.swing.JLabel();
        txtJudul2 = new javax.swing.JLabel();
        cmbTo = new javax.swing.JComboBox<>();
        cmbFrom = new javax.swing.JComboBox<>();
        btnConvert = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSupportedUnit = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(232, 240, 254));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(31, 41, 55));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_time.setBackground(new java.awt.Color(31, 41, 55));
        btn_time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_timeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_timeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_timeMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_time_35px.png"))); // NOI18N

        jLabel004.setBackground(new java.awt.Color(255, 255, 255));
        jLabel004.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel004.setForeground(new java.awt.Color(255, 255, 255));
        jLabel004.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel004.setText("Time");

        javax.swing.GroupLayout btn_timeLayout = new javax.swing.GroupLayout(btn_time);
        btn_time.setLayout(btn_timeLayout);
        btn_timeLayout.setHorizontalGroup(
            btn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_timeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel004)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        btn_timeLayout.setVerticalGroup(
            btn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_timeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_timeLayout.createSequentialGroup()
                        .addComponent(jLabel004)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 380, 70));

        btn_home.setBackground(new java.awt.Color(31, 41, 55));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_home_35px_1.png"))); // NOI18N

        jLabel005.setBackground(new java.awt.Color(255, 255, 255));
        jLabel005.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel005.setForeground(new java.awt.Color(255, 255, 255));
        jLabel005.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel005.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel005)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_homeLayout.createSequentialGroup()
                        .addComponent(jLabel005)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 380, 70));

        btn_data.setBackground(new java.awt.Color(31, 41, 55));
        btn_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dataMousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_save_as_35px.png"))); // NOI18N

        jLabel001.setBackground(new java.awt.Color(255, 255, 255));
        jLabel001.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel001.setForeground(new java.awt.Color(255, 255, 255));
        jLabel001.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel001.setText("Data");

        javax.swing.GroupLayout btn_dataLayout = new javax.swing.GroupLayout(btn_data);
        btn_data.setLayout(btn_dataLayout);
        btn_dataLayout.setHorizontalGroup(
            btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel001)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        btn_dataLayout.setVerticalGroup(
            btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dataLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_dataLayout.createSequentialGroup()
                        .addComponent(jLabel001)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 380, 70));

        btn_weight.setBackground(new java.awt.Color(31, 41, 55));
        btn_weight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_weightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_weightMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_weightMousePressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_weight_kg_35px.png"))); // NOI18N

        jLabel003.setBackground(new java.awt.Color(255, 255, 255));
        jLabel003.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel003.setForeground(new java.awt.Color(255, 255, 255));
        jLabel003.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel003.setText("Weight");

        javax.swing.GroupLayout btn_weightLayout = new javax.swing.GroupLayout(btn_weight);
        btn_weight.setLayout(btn_weightLayout);
        btn_weightLayout.setHorizontalGroup(
            btn_weightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_weightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel003)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        btn_weightLayout.setVerticalGroup(
            btn_weightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_weightLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_weightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_weightLayout.createSequentialGroup()
                        .addComponent(jLabel003)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 380, 70));

        btn_lenght.setBackground(new java.awt.Color(31, 41, 55));
        btn_lenght.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lenghtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lenghtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_lenghtMousePressed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_length_35px.png"))); // NOI18N

        jLabel002.setBackground(new java.awt.Color(255, 255, 255));
        jLabel002.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel002.setForeground(new java.awt.Color(255, 255, 255));
        jLabel002.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel002.setText("Lenght");

        javax.swing.GroupLayout btn_lenghtLayout = new javax.swing.GroupLayout(btn_lenght);
        btn_lenght.setLayout(btn_lenghtLayout);
        btn_lenghtLayout.setHorizontalGroup(
            btn_lenghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_lenghtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel002)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        btn_lenghtLayout.setVerticalGroup(
            btn_lenghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_lenghtLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btn_lenghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_lenghtLayout.createSequentialGroup()
                        .addComponent(jLabel002)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_lenght, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 380, 70));

        txtJudul.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtJudul.setForeground(new java.awt.Color(255, 255, 255));
        txtJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul.setText("Smart Converter");
        sidepane.add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, -1));
        sidepane.add(garis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 320, 10));

        btn_exit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        sidepane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 70, -1));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 380, 850));

        jPanel1.setBackground(new java.awt.Color(64, 74, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJudul1.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul1.setFont(new java.awt.Font("Lucida Fax", 1, 32)); // NOI18N
        txtJudul1.setForeground(new java.awt.Color(255, 255, 255));
        txtJudul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul1.setText("Time Converter");
        jPanel1.add(txtJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 280, 50));

        txtJudul2.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        txtJudul2.setForeground(new java.awt.Color(255, 255, 255));
        txtJudul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJudul2.setText("Choose unit, enter a value and convert it and get the result");
        jPanel1.add(txtJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 550, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 1320, 220));

        cmbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbToActionPerformed(evt);
            }
        });
        bg.add(cmbTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 190, 80));

        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFromActionPerformed(evt);
            }
        });
        bg.add(cmbFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 190, 80));

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });
        bg.add(btnConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 140, 50));

        txtInput.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bg.add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 190, 50));

        txtResult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });
        bg.add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 190, 50));

        txtSupportedUnit.setColumns(20);
        txtSupportedUnit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSupportedUnit.setRows(5);
        txtSupportedUnit.setText("Supported Units:\n• Second\n• Minute\n• Hour\n• Day\n");
        jScrollPane1.setViewportView(txtSupportedUnit);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 610, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Time_Machine_500px.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 390, 460, 440));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_arrow_100px_1.png"))); // NOI18N
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 140, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1302, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed
    
    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        setColor(btn_home);
       resetColor(btn_time);
       resetColor(btn_weight);
       resetColor(btn_lenght);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_timeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timeMouseEntered
        // TODO add your handling code here:
         setColor(btn_time);
       resetColor(btn_home);
       resetColor(btn_weight);
       resetColor(btn_lenght);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_timeMouseEntered

    private void btn_weightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weightMouseEntered
        // TODO add your handling code here:
         setColor(btn_weight);
       resetColor(btn_time);
       resetColor(btn_home);
       resetColor(btn_lenght);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_weightMouseEntered

    private void btn_lenghtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lenghtMouseEntered
        // TODO add your handling code here:
         setColor(btn_lenght);
       resetColor(btn_time);
       resetColor(btn_weight);
       resetColor(btn_home);
       resetColor(btn_data);
    }//GEN-LAST:event_btn_lenghtMouseEntered

    private void btn_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataMouseEntered
        // TODO add your handling code here:
         setColor(btn_data);
       resetColor(btn_time);
       resetColor(btn_weight);
       resetColor(btn_lenght);
       resetColor(btn_home);
    }//GEN-LAST:event_btn_dataMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        resetColor(btn_home);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_timeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timeMouseExited
        // TODO add your handling code here:
        resetColor(btn_time);
    }//GEN-LAST:event_btn_timeMouseExited

    private void btn_weightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weightMouseExited
        // TODO add your handling code here:
        resetColor(btn_weight);
    }//GEN-LAST:event_btn_weightMouseExited

    private void btn_lenghtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lenghtMouseExited
        // TODO add your handling code here:
        resetColor(btn_lenght);
    }//GEN-LAST:event_btn_lenghtMouseExited

    private void btn_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataMouseExited
        // TODO add your handling code here:
        resetColor(btn_data);
    }//GEN-LAST:event_btn_dataMouseExited

    private void btn_timeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timeMousePressed
        // TODO add your handling code here:
        time t = new time();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_timeMousePressed

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        SmartConverter h = new SmartConverter();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_weightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weightMousePressed
        // TODO add your handling code here:
        weight w = new weight();
        w.setVisible(true);
        w.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_weightMousePressed

    private void btn_lenghtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lenghtMousePressed
        // TODO add your handling code here:
        lenght l = new lenght();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_lenghtMousePressed

    private void btn_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataMousePressed
        // TODO add your handling code here:
        data d = new data();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_dataMousePressed

    private void cmbFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFromActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbFromActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
       if (cmbFrom.getSelectedIndex() == 0 || cmbTo.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this,
            "Pilih satuan waktu terlebih dahulu!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
        return;
        }
       
       double input;
       try{
           input = Double.parseDouble(txtInput.getText());
       } catch(NumberFormatException e) {
           JOptionPane.showMessageDialog(this,
                   "Masukkan angka yang valid!",
                   "Error",
                   JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       String from = cmbFrom.getSelectedItem().toString();
       String to = cmbTo.getSelectedItem().toString();
       
       double result = convert (input, from, to);
       
       if (Math.abs(result - Math.round(result)) < 1e-9) {
       txtResult.setText(String.valueOf((long) Math.round(result)));
       } else {
        DecimalFormat df = new DecimalFormat("#.########");
        txtResult.setText(df.format(result));
       }
    }//GEN-LAST:event_btnConvertActionPerformed

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultActionPerformed

    private void cmbToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbToActionPerformed
    
    
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(31,41,75));
    }
    
    void resetColor(JPanel panel){
         panel.setBackground(new Color(31,41,55));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnConvert;
    private javax.swing.JPanel btn_data;
    private javax.swing.JButton btn_exit;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_lenght;
    private javax.swing.JPanel btn_time;
    private javax.swing.JPanel btn_weight;
    private javax.swing.JComboBox<String> cmbFrom;
    private javax.swing.JComboBox<String> cmbTo;
    private javax.swing.JSeparator garis;
    private javax.swing.JLabel jLabel001;
    private javax.swing.JLabel jLabel002;
    private javax.swing.JLabel jLabel003;
    private javax.swing.JLabel jLabel004;
    private javax.swing.JLabel jLabel005;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTextField txtInput;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtJudul1;
    private javax.swing.JLabel txtJudul2;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextArea txtSupportedUnit;
    // End of variables declaration//GEN-END:variables
}
