/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author radit
 */
public class claim extends javax.swing.JFrame {

    /**
     * Creates new form lostnfound
     */
    public claim() {
        initComponents();
        
        loadComboBarangBelum();

        setPlaceholderTextField(txtNamaPengklaim, "Silahkan isi!");
        setPlaceholderTextField(txtKontak, "Silahkan isi!");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFound = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClaim = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnReport = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        compasLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNamaPengklaim = new javax.swing.JTextField();
        txtKontak = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBukti = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        dateClaim = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        cmbBarang = new javax.swing.JComboBox<>();
        btnAddClaim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(66, 71, 80));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 71, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(66, 71, 80));
        btnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_home_40px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOME");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 80, -1));

        btnFound.setBackground(new java.awt.Color(66, 71, 80));
        btnFound.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnFound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoundMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_backpack_40px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FOUND");

        javax.swing.GroupLayout btnFoundLayout = new javax.swing.GroupLayout(btnFound);
        btnFound.setLayout(btnFoundLayout);
        btnFoundLayout.setHorizontalGroup(
            btnFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnFoundLayout.setVerticalGroup(
            btnFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(btnFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        btnClaim.setBackground(new java.awt.Color(66, 71, 80));
        btnClaim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnClaim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClaimMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_badge_40px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CLAIM");

        javax.swing.GroupLayout btnClaimLayout = new javax.swing.GroupLayout(btnClaim);
        btnClaim.setLayout(btnClaimLayout);
        btnClaimLayout.setHorizontalGroup(
            btnClaimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnClaimLayout.setVerticalGroup(
            btnClaimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClaimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel7.getAccessibleContext().setAccessibleName("REPORT");

        jPanel1.add(btnClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        btnReport.setBackground(new java.awt.Color(66, 71, 80));
        btnReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Report_Card_40px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("REPORT");

        javax.swing.GroupLayout btnReportLayout = new javax.swing.GroupLayout(btnReport);
        btnReport.setLayout(btnReportLayout);
        btnReportLayout.setHorizontalGroup(
            btnReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnReportLayout.setVerticalGroup(
            btnReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_hole_40px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 40));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 630));

        compasLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compasLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_compass_80px.png"))); // NOI18N
        bg.add(compasLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 60));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CAMPUS LOST & FOUND");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 470, 60));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Claim Item");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, 50));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Claimant Name");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Claim Date");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Proof");
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Notes");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        txtNamaPengklaim.setText("jTextField1");
        bg.add(txtNamaPengklaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 1050, 40));

        txtKontak.setText("jTextField2");
        bg.add(txtKontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 480, 40));

        txtBukti.setColumns(20);
        txtBukti.setRows(5);
        jScrollPane1.setViewportView(txtBukti);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 480, -1));

        txtCatatan.setColumns(20);
        txtCatatan.setRows(5);
        jScrollPane2.setViewportView(txtCatatan);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 250, -1));
        bg.add(dateClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 540, 40));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Item Found");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, -1, -1));

        cmbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bg.add(cmbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 250, -1));

        btnAddClaim.setText("Add");
        btnAddClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClaimActionPerformed(evt);
            }
        });
        bg.add(btnAddClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        lostnfound lf = new lostnfound();
        lf.setVisible(true);
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnFoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoundMouseClicked
        // TODO add your handling code here:
        found f = new found();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnFoundMouseClicked

    private void btnClaimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClaimMouseClicked
        // TODO add your handling code here:
        claim c = new claim();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnClaimMouseClicked

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        // TODO add your handling code here:
        report r = new report();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnReportMouseClicked

    private void btnAddClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClaimActionPerformed
        // TODO add your handling code here:
         int idx = cmbBarang.getSelectedIndex();
    if (idx < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih barang yang akan diklaim!");
        return;
    }

    int idBarang = listIdBarang.get(idx);

    String namaPengklaim = txtNamaPengklaim.getText().trim();
    String kontak = txtKontak.getText().trim();
    java.util.Date utilDate = dateClaim.getDate();
    String bukti = txtBukti.getText().trim();
    String catatan = txtCatatan.getText().trim();

    if (namaPengklaim.isEmpty() || utilDate == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nama Pengklaim dan Tanggal Klaim wajib diisi!");
        return;
    }

    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

    new InsertClaim().insertClaim(idBarang, namaPengklaim, kontak, sqlDate, bukti, catatan);

    // reset form claim
    txtNamaPengklaim.setText("");
    txtKontak.setText("");
    txtBukti.setText("");
    txtCatatan.setText("");
    dateClaim.setDate(null);

    // refresh combo: barang yg sudah diklaim hilang
    loadComboBarangBelum();
    }//GEN-LAST:event_btnAddClaimActionPerformed

    private void setPlaceholderTextField(javax.swing.JTextField field, String placeholder) {
    field.setText(placeholder);
    field.setForeground(java.awt.Color.GRAY);

    field.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(java.awt.Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (field.getText().trim().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(java.awt.Color.GRAY);
            }
        }
    });
}

    
    private java.util.ArrayList<Integer> listIdBarang = new java.util.ArrayList<>();

    
    private void loadComboBarangBelum() {
    listIdBarang.clear();
    cmbBarang.removeAllItems();

    String sql = "SELECT id_barang, nama_barang, lokasi_ditemukan, tanggal_ditemukan " +
                 "FROM barang_temuan WHERE status_barang='BELUM' ORDER BY id_barang DESC";

    try {
        Koneksi k = new Koneksi();
        k.koneksi();

        java.sql.PreparedStatement ps = k.con.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            int id = rs.getInt("id_barang");
            String label = rs.getString("nama_barang") + " - " +
                           rs.getString("lokasi_ditemukan") + " - " +
                           rs.getDate("tanggal_ditemukan");

            listIdBarang.add(id);
            cmbBarang.addItem(label);
        }

        rs.close();
        ps.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal load barang: " + e.getMessage());
    }
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lostnfound().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAddClaim;
    private javax.swing.JPanel btnClaim;
    private javax.swing.JPanel btnFound;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnReport;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JLabel compasLogo;
    private com.toedter.calendar.JDateChooser dateClaim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtBukti;
    private javax.swing.JTextArea txtCatatan;
    private javax.swing.JTextField txtKontak;
    private javax.swing.JTextField txtNamaPengklaim;
    // End of variables declaration//GEN-END:variables
}
