/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author radit
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form lostnfound
     */
    public report() {
        initComponents();
        
        loadTableFound();
        loadTableClaim();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFound = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClaim = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnReport = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        compasLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClaim = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFound = new javax.swing.JTable();
        btnDeleteFound = new javax.swing.JButton();
        btnDeleteClaim = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnUpdateFound = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(66, 71, 80));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 71, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(66, 71, 80));
        btnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_home_40px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOME");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 80, -1));

        btnFound.setBackground(new java.awt.Color(66, 71, 80));
        btnFound.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnFound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoundMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_backpack_40px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FOUND");

        javax.swing.GroupLayout btnFoundLayout = new javax.swing.GroupLayout(btnFound);
        btnFound.setLayout(btnFoundLayout);
        btnFoundLayout.setHorizontalGroup(
            btnFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnFoundLayout.setVerticalGroup(
            btnFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(btnFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        btnClaim.setBackground(new java.awt.Color(66, 71, 80));
        btnClaim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnClaim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClaimMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_badge_40px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CLAIM");

        javax.swing.GroupLayout btnClaimLayout = new javax.swing.GroupLayout(btnClaim);
        btnClaim.setLayout(btnClaimLayout);
        btnClaimLayout.setHorizontalGroup(
            btnClaimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnClaimLayout.setVerticalGroup(
            btnClaimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClaimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel7.getAccessibleContext().setAccessibleName("REPORT");

        jPanel1.add(btnClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        btnReport.setBackground(new java.awt.Color(66, 71, 80));
        btnReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Report_Card_40px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("REPORT");

        javax.swing.GroupLayout btnReportLayout = new javax.swing.GroupLayout(btnReport);
        btnReport.setLayout(btnReportLayout);
        btnReportLayout.setHorizontalGroup(
            btnReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnReportLayout.setVerticalGroup(
            btnReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_hole_40px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 40));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 630));

        compasLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compasLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_compass_80px.png"))); // NOI18N
        bg.add(compasLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 60));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CAMPUS LOST & FOUND");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 470, 60));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Reports");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 250, 50));

        tblClaim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClaim);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 580, 290));

        tblFound.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFoundMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFound);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 560, 290));

        btnDeleteFound.setText("Delete");
        btnDeleteFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFoundActionPerformed(evt);
            }
        });
        bg.add(btnDeleteFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        btnDeleteClaim.setText("Delete");
        btnDeleteClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClaimActionPerformed(evt);
            }
        });
        bg.add(btnDeleteClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Claimed Table");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FOUND Table");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, -1));

        btnUpdateFound.setText("Update");
        btnUpdateFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFoundActionPerformed(evt);
            }
        });
        bg.add(btnUpdateFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        lostnfound lf = new lostnfound();
        lf.setVisible(true);
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnFoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoundMouseClicked
        // TODO add your handling code here:
        found f = new found();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnFoundMouseClicked

    private void btnClaimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClaimMouseClicked
        // TODO add your handling code here:
        claim c = new claim();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnClaimMouseClicked

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        // TODO add your handling code here:
        report r = new report();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnReportMouseClicked

    private void btnDeleteFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFoundActionPerformed
        // TODO add your handling code here:
         int row = tblFound.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data Found yang mau dihapus!");
        return;
    }

    int idBarang = Integer.parseInt(tblFound.getValueAt(row, 0).toString()); // kolom 0 = ID

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin hapus barang ID " + idBarang + "?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM barang_temuan WHERE id_barang=?";

    try {
        Koneksi k = new Koneksi();
        k.koneksi();

        java.sql.PreparedStatement ps = k.con.prepareStatement(sql);
        ps.setInt(1, idBarang);
        ps.executeUpdate();
        ps.close();

        javax.swing.JOptionPane.showMessageDialog(this, "Data Found berhasil dihapus!");

        // refresh tabel
        loadTableFound();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal hapus Found: " + e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteFoundActionPerformed

    private void btnDeleteClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClaimActionPerformed
        // TODO add your handling code here:
        int row = tblClaim.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data Claim yang mau dihapus!");
        return;
    }

    int idKlaim = Integer.parseInt(tblClaim.getValueAt(row, 0).toString());  // kolom 0 = id_klaim
    int idBarang = Integer.parseInt(tblClaim.getValueAt(row, 1).toString()); // kolom 1 = id_barang

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin hapus klaim ID " + idKlaim + " ?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    String sqlDelete = "DELETE FROM klaim WHERE id_klaim=?";
    String sqlUpdate = "UPDATE barang_temuan SET status_barang='BELUM' WHERE id_barang=?";

    try {
        Koneksi k = new Koneksi();
        k.koneksi();
        k.con.setAutoCommit(false);

        java.sql.PreparedStatement ps1 = k.con.prepareStatement(sqlDelete);
        ps1.setInt(1, idKlaim);
        ps1.executeUpdate();
        ps1.close();

        java.sql.PreparedStatement ps2 = k.con.prepareStatement(sqlUpdate);
        ps2.setInt(1, idBarang);
        ps2.executeUpdate();
        ps2.close();

        k.con.commit();
        k.con.setAutoCommit(true);

        javax.swing.JOptionPane.showMessageDialog(this, "Claim berhasil dihapus & status barang kembali BELUM!");

        // refresh tabel
        loadTableClaim();
        loadTableFound();

    } catch (Exception e) {
        try { 
            // rollback kalau gagal
            // (kalau koneksi null, ignore)
        } catch (Exception ex) {}
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal hapus Claim: " + e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteClaimActionPerformed

    private void btnUpdateFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFoundActionPerformed
        // TODO add your handling code here:
         updateFoundFromTable();
    }//GEN-LAST:event_btnUpdateFoundActionPerformed

    private void tblFoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFoundMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblFoundMouseClicked

    private void updateFoundFromTable() {
    int row = tblFound.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data Found di tabel dulu!");
        return;
    }

    // ambil data dari tabel (sesuaikan index kolom)
    int idBarang = Integer.parseInt(tblFound.getValueAt(row, 0).toString());
    String namaBarang = tblFound.getValueAt(row, 1).toString();
    String kategori = tblFound.getValueAt(row, 2).toString();
    String lokasi = tblFound.getValueAt(row, 3).toString();
    String tanggal = tblFound.getValueAt(row, 4).toString(); // format YYYY-MM-DD
    String status = tblFound.getValueAt(row, 5).toString();  // BELUM/SUDAH

    // optional: larang update kalau SUDAH
    if (status.equalsIgnoreCase("SUDAH")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Barang sudah diklaim (SUDAH), tidak bisa diupdate!");
        return;
    }

    // input baru lewat dialog
    String newNama = javax.swing.JOptionPane.showInputDialog(this, "Update Nama Barang:", namaBarang);
    if (newNama == null) return; // cancel

    String newKategori = javax.swing.JOptionPane.showInputDialog(this, "Update Kategori:", kategori);
    if (newKategori == null) return;

    String newLokasi = javax.swing.JOptionPane.showInputDialog(this, "Update Lokasi Ditemukan:", lokasi);
    if (newLokasi == null) return;

    String newTanggal = javax.swing.JOptionPane.showInputDialog(this, "Update Tanggal (YYYY-MM-DD):", tanggal);
    if (newTanggal == null) return;

    // validasi sederhana
    if (newNama.trim().isEmpty() || newLokasi.trim().isEmpty() || newTanggal.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Input tidak boleh kosong!");
        return;
    }

    String sql = "UPDATE barang_temuan " +
                 "SET nama_barang=?, kategori=?, lokasi_ditemukan=?, tanggal_ditemukan=? " +
                 "WHERE id_barang=?";

    try {
        Koneksi k = new Koneksi();
        k.koneksi();

        java.sql.PreparedStatement ps = k.con.prepareStatement(sql);
        ps.setString(1, newNama.trim());
        ps.setString(2, newKategori.trim());
        ps.setString(3, newLokasi.trim());
        ps.setString(4, newTanggal.trim()); // karena format string YYYY-MM-DD
        ps.setInt(5, idBarang);

        ps.executeUpdate();
        ps.close();

        javax.swing.JOptionPane.showMessageDialog(this, "Data Found berhasil diupdate!");

        // refresh table
        loadTableFound();
        loadTableClaim();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal update Found: " + e.getMessage());
    }
}

    
    private void loadTableFound() {
    String[] kolom = {"ID", "Nama Barang", "Kategori", "Lokasi", "Tanggal", "Status"};
    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(null, kolom) {
                @Override public boolean isCellEditable(int row, int col) { return false; }
            };

    String sql = "SELECT id_barang, nama_barang, kategori, lokasi_ditemukan, tanggal_ditemukan, status_barang " +
                 "FROM barang_temuan ORDER BY id_barang DESC";

    try {
        Koneksi k = new Koneksi();
        k.koneksi();

        java.sql.PreparedStatement ps = k.con.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id_barang"),
                rs.getString("nama_barang"),
                rs.getString("kategori"),
                rs.getString("lokasi_ditemukan"),
                rs.getDate("tanggal_ditemukan"),
                rs.getString("status_barang")
            };
            model.addRow(row);
        }

        rs.close();
        ps.close();

        tblFound.setModel(model);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal load Found: " + e.getMessage());
    }
}

    private void loadTableClaim() {
    String[] kolom = {"Claim ID", "ID Barang", "Nama Barang", "Nama Pengklaim", "Kontak", "Tanggal Klaim", "Bukti", "Catatan"};
    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(null, kolom) {
                @Override public boolean isCellEditable(int row, int col) { return false; }
            };

    String sql = "SELECT k.id_klaim, k.id_barang, b.nama_barang, k.nama_pengklaim, k.kontak, k.tanggal_klaim, k.bukti, k.catatan " +
                 "FROM klaim k " +
                 "JOIN barang_temuan b ON k.id_barang = b.id_barang " +
                 "ORDER BY k.id_klaim DESC";

    try {
        Koneksi k = new Koneksi();
        k.koneksi();

        java.sql.PreparedStatement ps = k.con.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id_klaim"),
                rs.getInt("id_barang"),
                rs.getString("nama_barang"),
                rs.getString("nama_pengklaim"),
                rs.getString("kontak"),
                rs.getDate("tanggal_klaim"),
                rs.getString("bukti"),
                rs.getString("catatan")
            };
            model.addRow(row);
        }

        rs.close();
        ps.close();

        tblClaim.setModel(model);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal load Claim: " + e.getMessage());
    }
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lostnfound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lostnfound().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnClaim;
    private javax.swing.JButton btnDeleteClaim;
    private javax.swing.JButton btnDeleteFound;
    private javax.swing.JPanel btnFound;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnReport;
    private javax.swing.JButton btnUpdateFound;
    private javax.swing.JLabel compasLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClaim;
    private javax.swing.JTable tblFound;
    // End of variables declaration//GEN-END:variables
}
